name: CI/CD Pipeline

# 트리거: main 브랜치에 push될 때 작동
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
            npm install

    - name: Lint
      run: |
            npm run lint

    # 2. 빌드
    - name: Build project
      run: |
            npm run build

    # 3. GitHub Pages로 배포
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        publish_dir: ./dist  # 빌드 결과물이 생성되는 디렉토리 (예시)
